import { CrapReport } from "../models.js";
import { SlopguardErrorEnvelope } from "../errors.js";
import { SlopguardVersion } from "../version.js";

/**
 * Pure renderers for `CrapReport`. Lives in core so the CLI's `analyze`
 * command stays a thin shim — and so the formatters can be unit-tested
 * without piping real stdout. Two outputs: a human-readable text block and
 * canonical JSON.
 */

/**
 * Pretty text rendering — leading metadata, a summary table, then the top-N
 * methods by wCRAP descending. Methods above threshold are marked with `!`
 * so the table works as a "where to go next" guide even when no method is
 * strictly crappy.
 */
export function prettyReport(report: CrapReport, topN = 20): string {
  let out = "";
  out += header(report);
  out += "\n";
  if (report.notes.length > 0) {
    out += notes(report);
    out += "\n";
  }
  out += summary(report);
  out += "\n";
  out += topMethodsByCrap(report, topN);
  return out;
}

/** Canonical JSON encoding — sorted keys to keep the output diff-friendly in CI. */
export function jsonReport(report: CrapReport, prettyPrinted = true): string {
  return stableStringify(report, prettyPrinted ? 2 : 0);
}

/** Render an error envelope as a single-line CLI message. */
export function errorText(envelope: SlopguardErrorEnvelope): string {
  return `${SlopguardVersion.toolName}: [${envelope.code}] ${envelope.message}`;
}

/** Render an error envelope as JSON. */
export function errorJSON(envelope: SlopguardErrorEnvelope): string {
  return stableStringify({ error: envelope }, 2);
}

// MARK: - Text helpers

function header(report: CrapReport): string {
  let coverageLine: string;
  if (report.coverageDataPath !== null) {
    coverageLine = report.coverageDataPath;
  } else if (report.coverageAvailable) {
    coverageLine = "(generated by the test runner — cleaned up after run)";
  } else {
    coverageLine = "(none — coverage assumed 0%)";
  }
  return (
    `${SlopguardVersion.toolName} ${report.toolVersion} — schema ${report.schemaVersion}\n` +
    `source:    ${report.sourceRoot}\n` +
    `coverage:  ${coverageLine}\n` +
    `threshold: ${report.threshold.toFixed(1)}\n`
  );
}

function notes(report: CrapReport): string {
  let out = "Notes\n";
  for (const note of report.notes) {
    out += `  • ${note}\n`;
  }
  return out;
}

function summary(report: CrapReport): string {
  const s = report.summary;
  let out = "Summary\n";
  out += `  files:     ${s.fileCount}\n`;
  out += `  types:     ${s.typeCount}  (crappy: ${s.crappyTypeCount})\n`;
  out += `  methods:   ${s.methodCount}  (crappy: ${s.crappyMethodCount})\n`;
  out += `  avg crap:  ${s.averageCrap.toFixed(2)}\n`;
  out += `  max crap:  ${s.maxCrap.toFixed(2)}\n`;
  out += `  avg cyc:   ${s.averageComplexity.toFixed(2)}\n`;
  out += `  avg cog:   ${s.averageCognitiveComplexity.toFixed(2)}\n`;
  out += `  avg wt:    ${s.averageWeightedComplexity.toFixed(2)}\n`;
  if (s.weightedCoverage !== null) {
    out += `  coverage:  ${s.weightedCoverage.toFixed(1)}%\n`;
  } else {
    out += "  coverage:  unavailable (run without --no-coverage to gather it)\n";
  }
  return out;
}

function topMethodsByCrap(report: CrapReport, topN: number): string {
  const ranked = [...report.methods].sort((a, b) => b.crap - a.crap).slice(0, topN);
  if (ranked.length === 0) {
    return "No methods analyzed.\n";
  }
  const crappyTotal = report.summary.crappyMethodCount;
  const thresholdText = report.threshold.toFixed(1);
  const headerLine =
    crappyTotal > 0
      ? `Top methods by wCRAP (${crappyTotal} above threshold ${thresholdText}, marked !)`
      : `Top methods by wCRAP (none above threshold ${thresholdText} — ranked hotspots to watch)`;
  let out = `${headerLine}\n`;
  for (const m of ranked) {
    // cyc=cyclomatic, cog=cognitive, wt=weighted. Skew between cyc and cog
    // tells the reader whether a high CRAP is real (both high) or a
    // flat-dispatch artefact (cyc high, cog low → wt small → CRAP is honest).
    const marker = m.isCrappy ? "!" : " ";
    out +=
      `${marker} ${m.crap.toFixed(2).padStart(7)}  ` +
      `cyc=${String(m.complexity).padEnd(3)} ` +
      `cog=${String(m.cognitiveComplexity).padEnd(3)} ` +
      `wt=${m.weightedComplexity.toFixed(2).padStart(5)} ` +
      `cov=${m.coverage.toFixed(1).padStart(5)}%  ` +
      `${m.file}:${m.line}  ${m.qualifiedName}\n`;
  }
  return out;
}

/** JSON.stringify with lexicographically sorted keys at every level. */
function stableStringify(value: unknown, indent: number): string {
  const sortKeys = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(sortKeys);
    if (v !== null && typeof v === "object") {
      const entries = Object.entries(v as Record<string, unknown>).sort(([a], [b]) =>
        /* v8 ignore next -- the `0` tiebreaker can't fire: object keys are unique */
        a < b ? -1 : a > b ? 1 : 0
      );
      return Object.fromEntries(entries.map(([k, val]) => [k, sortKeys(val)]));
    }
    return v;
  };
  return indent > 0 ? JSON.stringify(sortKeys(value), null, indent) : JSON.stringify(sortKeys(value));
}
