import { describe, expect, it } from "vitest";
import { CrapAggregator } from "../src/core/aggregation/crapAggregator.js";
import {
  errorJSON,
  errorText,
  jsonReport,
  prettyReport,
} from "../src/core/formatting/crapReportFormatter.js";
import { makeMethodMetric } from "../src/core/models.js";

function sampleReport(coverage: boolean) {
  const method = makeMethodMetric({
    name: "tangled",
    qualifiedName: "Thing.tangled",
    typeName: "Thing",
    kind: "method",
    file: "thing.ts",
    startLine: 3,
    endLine: 40,
    complexity: 12,
    cognitiveComplexity: 15,
  });
  return new CrapAggregator().aggregate({
    fileReports: [{ path: "thing.ts", methods: [method], types: [] }],
    sourceRoot: "/proj",
    coverageDataPath: null,
    coverage: coverage ? { methodCoverage: () => 10, fileCoverage: () => 10 } : null,
    generatedAt: new Date("2026-01-02T03:04:05Z"),
  });
}

describe("prettyReport", () => {
  it("renders header, summary, and the ranked table", () => {
    const out = prettyReport(sampleReport(false));
    expect(out).toContain("slopguard-typescript 0.1.0 — schema 2");
    expect(out).toContain("source:    /proj");
    expect(out).toContain("coverage:  (none — coverage assumed 0%)");
    expect(out).toContain("threshold: 30.0");
    expect(out).toContain("methods:   1  (crappy: 1)");
    expect(out).toContain("coverage:  unavailable (run without --no-coverage to gather it)");
    expect(out).toContain("Top methods by wCRAP (1 above threshold 30.0, marked !)");
    expect(out).toContain("thing.ts:3");
    expect(out).toContain("Thing.tangled");
    expect(out).toMatch(/!\s+\d+\.\d{2}\s+cyc=12/);
  });

  it("reports the ephemeral-coverage header line when coverage was gathered", () => {
    const out = prettyReport(sampleReport(true));
    expect(out).toContain("coverage:  (generated by the test runner — cleaned up after run)");
    expect(out).toContain("coverage:  10.0%");
  });

  it("renders a hotspot header when nothing is above threshold", () => {
    const report = new CrapAggregator().aggregate({
      fileReports: [
        {
          path: "a.ts",
          methods: [
            makeMethodMetric({
              name: "ok",
              qualifiedName: "ok",
              typeName: null,
              kind: "function",
              file: "a.ts",
              startLine: 1,
              endLine: 2,
              complexity: 1,
              cognitiveComplexity: 0,
            }),
          ],
          types: [],
        },
      ],
      sourceRoot: "/proj",
      coverageDataPath: null,
      coverage: null,
    });
    expect(prettyReport(report)).toContain("none above threshold 30.0 — ranked hotspots to watch");
  });

  it("says so when no methods were analyzed", () => {
    const report = new CrapAggregator().aggregate({
      fileReports: [],
      sourceRoot: "/proj",
      coverageDataPath: null,
      coverage: null,
    });
    expect(prettyReport(report)).toContain("No methods analyzed.");
  });
});

describe("jsonReport", () => {
  it("emits stable sorted keys and the schema fields", () => {
    const text = jsonReport(sampleReport(false));
    const parsed = JSON.parse(text);
    expect(parsed.schemaVersion).toBe("2");
    expect(parsed.tool).toBe("slopguard-typescript");
    expect(parsed.generatedAt).toBe("2026-01-02T03:04:05.000Z");
    expect(parsed.methods[0].qualifiedName).toBe("Thing.tangled");
    const keys = Object.keys(parsed);
    expect(keys).toEqual([...keys].sort());
  });
});

describe("error rendering", () => {
  it("renders single-line text", () => {
    expect(errorText({ code: "file_not_found", message: "File not found: /x" })).toBe(
      "slopguard-typescript: [file_not_found] File not found: /x"
    );
  });

  it("renders the JSON envelope", () => {
    const parsed = JSON.parse(errorJSON({ code: "unsupported", message: "nope" }));
    expect(parsed).toEqual({ error: { code: "unsupported", message: "nope" } });
  });
});
